package circus;

public enum State {
    MAIN_MENU,
    PLAY_MENU,
    GAME_BROWSER_MENU,
    MAIN_LOBBY_MENU,
    SETTINGS_MAIN_MENU,
    SETTINGS_PRESETS_MENU,
    SETTINGS_LOBBY_MENU,
    SETTINGS_MAPS_MENU,
    SETTINGS_HEROES_MENU,
    SETTINGS_MODES_MENU,
    SETTINGS_WORKSHOP_MENU
}
